# Generated by Django 5.0.7 on 2024-09-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_patient_patientph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorPh',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientPh',
            field=models.CharField(max_length=11),
        ),
    ]
